CREATE TABLE CONUSER
(
    ID INT(10) PRIMARY KEY AUTO_INCREMENT,
    LOGIN VARCHAR(20) NOT NULL,
    PASSWORD VARCHAR(30) NOT NULL,
    TYPE VARCHAR(4) NOT NULL,
    BLOCKED INT(1) NOT NULL
);

CREATE TABLE POST
(
  ID INT(10) PRIMARY KEY AUTO_INCREMENT,
  AUTHOR_ID INT(10) NOT NULL,
  ABSTRACT VARCHAR(400) NOT NULL,
  FILENAME VARCHAR(80) NOT NULL,
  PUBLICATED DATE NOT NULL,
  STATE INT(1) NOT NULL,
  CONSTRAINT POST_conuser_ID_fk FOREIGN KEY (AUTHOR_ID) REFERENCES conuser (ID)
);

CREATE TABLE REVIEW
(
  ID INT(10) PRIMARY KEY AUTO_INCREMENT,
  AUTHOR_ID INT(10) NOT NULL,
  POST_ID INT(10) NOT NULL,
  TEXT VARCHAR(600) NOT NULL,
  VERDICT INT(1) NOT NULL,
  LOCKED INT(1) NOT NULL,
  PUBLICATED DATE NOT NULL,
  CONSTRAINT REVIEW_conuser_ID_fk FOREIGN KEY (AUTHOR_ID) REFERENCES conuser (ID),
  CONSTRAINT REVIEW_post_ID_fk FOREIGN KEY (POST_ID) REFERENCES post (ID)
);
