INSERT INTO CONUSER (ID,  LOGIN, PASSWORD, TYPE, BLOCKED) VALUES (1701, 'Rev1', '111', 'REV', 0);
INSERT INTO CONUSER (ID,  LOGIN, PASSWORD, TYPE, BLOCKED) VALUES (1702, 'Rev2', '222', 'REV', 0);
INSERT INTO CONUSER (ID,  LOGIN, PASSWORD, TYPE, BLOCKED) VALUES (1703, 'Aut1', '111', 'AUT', 0);
INSERT INTO CONUSER (ID,  LOGIN, PASSWORD, TYPE, BLOCKED) VALUES (1704, 'Aut2', '222', 'AUT', 0);
INSERT INTO CONUSER (ID,  LOGIN, PASSWORD, TYPE, BLOCKED) VALUES (1705, 'Rev3', '333', 'REV', 0);

INSERT INTO POST (ID,  AUTHOR_ID, ABSTRACT, FILENAME, PUBLICATED, STATE, TITLE)
  VALUES (1701, 1703, 'This is abstract of post 1.', '1.pdf', NOW(), 0, 'Post 1');
INSERT INTO POST (ID,  AUTHOR_ID, ABSTRACT, FILENAME, PUBLICATED, STATE, TITLE)
  VALUES (1702, 1703, 'This is abstract of post 2.', '2.pdf', NOW(), 0, 'Post 2');
INSERT INTO POST (ID,  AUTHOR_ID, ABSTRACT, FILENAME, PUBLICATED, STATE, TITLE)
  VALUES (1703, 1704, 'This is abstract of post 3.', '3.pdf', NOW(), 0, 'Post 3');
INSERT INTO POST (ID,  AUTHOR_ID, ABSTRACT, FILENAME, PUBLICATED, STATE, TITLE)
  VALUES (1704, 1704, 'This is abstract of post 4.', '4.pdf', NOW(), 0, 'Post 4');

INSERT INTO ASSIGNMENT (ID, POST_ID, REVIEWER_ID)
  VALUES (1701, 1701, 1701);
INSERT INTO ASSIGNMENT (ID, POST_ID, REVIEWER_ID)
  VALUES (1702, 1701, 1702);
INSERT INTO ASSIGNMENT (ID, POST_ID, REVIEWER_ID)
  VALUES (1703, 1701, 1705);

